<?php
/**
 * @var string $identity - На какой email отправлена ссылка для восстановления пароля
 */
?>
<div class="jumbotron z-depth-2">
    <p class="lead">
        <?= sprintf($this->translate('An email has been sent to %s.'), '<a href="javascript:void();">' . $identity . '</a>') ?>
    </p>
    <p><?= $this->translate('It includes information on changing and confirming your new password.'); ?></p>
    <hr class="my-3">
    <p><?= $this->translate('If none of the above helps, please contact our support team'); ?></p>
</div>
