<?php
/**
 * @var \Application\Entity\Client[]     $clients
 * @var string                             $search значение поискового поля
 */

/** @var \Application\View\Helper\Navigation\Navbar $menu */
$menu = $this->navigation('Zend\Navigation\Default')->Navbar();
$menu->setActiveItemId('clients');

$this->headLink()->appendStylesheet($this->basePath('css/contragents.css'));
$this->inlineScript()->appendFile($this->basePath('js/contragents.js'));
?>
<div class="row mb-3">
    <div class="col-4">
        <form class="form" action="?" method="get">
            <div class="input-group search-input-group">
                <div class="input-group-prepend">
                    <div class="input-group-text"><i class="material-icons">&#xE8B6;</i></div>
                </div>
                <input class="form-control search-field" type="text" name="search" placeholder="Поиск по названию или ИНН" value="<?= $search; ?>">
            </div>

            <!--For submit by enter key-->
            <input type="submit" style="display:none"/>
        </form>
    </div>
</div>

<?php if(empty($clients)): ?>
    <div class="alert alert-dark" role="alert">
        Нет данных для отображения
    </div>
<?php else: ?>
    <table class="table table-hover table-contragents">
        <thead>
        <tr>
            <th>Наименование клиента</th>
            <th>ИНН</th>
            <th>КПП</th>
            <th>Дата регистрации</th>
        </tr>
        </thead>
        <tbody>
        <tbody>
        <?php foreach ($clients as $client): ?>
            <?= $this->partial('application/clients/partial/row', [
                'client' => $client,
            ]); ?>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

