<?php
/**
 * @var \Application\Entity\Client   $client
 * @var string                         $activeTab
 */

/** @var \Application\View\Helper\Navigation\Navbar $menu */
$menu = $this->navigation('Zend\Navigation\Default')->Navbar();
$menu->setActiveItemId('clients');

$this->headLink()->appendStylesheet($this->basePath('css/contragents.css'));
$this->inlineScript()->appendFile($this->basePath('js/contragents.js'));
?>

<!--client info-->
<div class="contragent_info">
    <?= $this->partial('application/clients/partial/header', [
        'client'  => $client,
        'activeTab' => $activeTab,
    ]); ?>

    <!--Инфо провайдера-->
    <div class="row">
        <div class="col-md-4 col-sm-6 col-6">
            <p class="label">ИНН</p>
            <p class="label">КПП</p>
        </div>
        <div class="col-md-8 col-sm-6 col-6">
            <p class="value"><?= $client->getInn(); ?></p>
            <p class="value"><?= $client->getKpp(); ?></p>
        </div>
    </div>
</div>
