<?php
/**
 * @var \Application\Entity\Provider $provider
 * @var \Application\Entity\User     $users
 * @var \Zend\Form\Form              $newUserForm
 * @var \Zend\Form\Form              $updateUserForm
 * @var string                       $activeTab
 */

/** @var \Application\View\Helper\Navigation\Navbar $menu */
$menu = $this->navigation('Zend\Navigation\Default')->Navbar();
$menu->setActiveItemId('users');

$this->headLink()->appendStylesheet($this->basePath('css/contragents.css'));
$this->inlineScript()->appendFile($this->basePath('js/users.js'));
?>

    <!--provider info-->
    <div class="contragent_info">
        <?= $this->partial('application/providers/partial/header', [
            'provider'  => $provider,
            'activeTab' => $activeTab,
        ]); ?>

        <div class="row">
            <div class="col-12 text-right">
                <?php if($this->isGranted('users.add')): ?>
                    <button type="button" class="btn btn-raised btn-primary btn-blue pull-right" id="addUserBtn">Добавить пользователя</button>
                <?php endif; ?>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <?php if(empty($users)): ?>
                    <div class="alert alert-dark" role="alert">
                        Нет данных для отображения
                    </div>
                <?php else: ?>

                    <div class="row user-cards">
                        <?php foreach ($users as $user): ?>
                            <?= $this->partial('application/users/partial/row', [
                                'user' => $user,
                            ]); ?>
                        <?php endforeach; ?>
                    </div>

                <?php endif; ?>
            </div>
        </div>
    </div>

<?php if($this->isGranted('users.add')): ?>
    <!-- Modal add new user -->
    <?= $this->partial('application/users/partial/modal', [
        'newUserForm' => $newUserForm,
    ]); ?>


    <!-- Modal edit user -->
    <?= $this->partial('application/users/partial/editModal', [
        'updateUserForm' => $updateUserForm,
    ]); ?>
<?php endif; ?>
