<?php
/** @var \Application\Entity\User $user */
$user = $this->zfbUserIdentity();

// Достыпные локали
$locales = $this->layout()->locales;
//Текущая локаль
$currentLocale = $this->layout()->currentLocale;

/** @var \Zend\View\Helper\Navigation\Menu $menu */
//$menu = $this->navigation('Zend\Navigation\Default')->menu();
//$menu->setLiActiveClass('active');
//$menu->setUlClass('navbar-nav mr-auto menu');


/** @var \Application\View\Helper\Navigation\Navbar $menu */
$menu = $this->navigation('Zend\Navigation\Default')->Navbar();
$menu->setClassToAItem('nav-link') // applied to <a> element
->setUlClass('navbar-nav mr-auto ml-auto menu')
    ->setAddClassToListItem(true)
    ->setLiActiveClass('active');
?>

<nav class="navbar navbar-expand-md navbar-light bg-light fixed-top">
        <a class="navbar-brand" href="<?=$this->url('home'); ?>">
            <img src="<?= $this->basePath('img/logo.svg') ?>" alt="" />
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <?= $menu->render(); ?>

            <?php if ($user): ?>
                <ul class="nav navbar-nav pull-right user-menu">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="userMenuLabel" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="user-name"><?= $this->zfbUserDisplayName(); ?></span>

                            <?php if ($user->getContragentName()): ?>
                                <br/><span class="contragent-name"><?= $user->getContragentName(); ?></span>
                            <?php endif; ?>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="userMenuLabel">
                            <li><a class="dropdown-item dark" href="<?= $this->url('zfbuser/logout'); ?>">Выход</a></li>
                        </ul>
                    </li>
                </ul>
            <?php endif; ?>
        </div>
</nav>
