<?php
/** @var \Application\Entity\User $user */
$user = $this->zfbUserIdentity();

// Достыпные локали
$locales = $this->layout()->locales;
//Текущая локаль
$currentLocale = $this->layout()->currentLocale;

/** @var \Zend\View\Helper\Navigation\Menu $menu */
$menu = $this->navigation('Zend\Navigation\Default')->menu();
$menu->setLiActiveClass('active');
$menu->setUlClass('nav navbar-nav menu');
?>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mainMenu"
                    aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?= $this->url('home') ?>">
                <img src="<?= $this->basePath('img/logo.svg') ?>" alt="" />
                <!--&nbsp;Биллинг<small>Биллинг</small>-->
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="mainMenu">
            <?= $menu->render(); ?>

            <?php if ($user): ?>
                <ul class="nav navbar-nav navbar-right user-menu">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">
                            <?= $this->zfbUserDisplayName(); ?>

                            <?php if ($user->getContragentName()): ?>
                                <br/><span><?= $user->getContragentName(); ?></span>
                            <?php endif; ?>
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item dark" href="<?= $this->url('zfbuser/logout'); ?>">Выход</a></li>
                        </ul>
                    </li>
                </ul>
            <?php endif; ?>
        </div>
    </div>
</nav>
