<?php
/**
 * @var \Application\Entity\Provider $provider
 * @var string                       $activeTab
 */
?>

<a href="<?= $this->url('providers'); ?>" class="back_link">
    <i class="material-icons">arrow_back</i>
    К списку
</a>

<div class="row">
    <div class="col-md-12">
        <h1 class="title"><?= $provider->getFullName(); ?><br>
            <small>зарегистрирован <?= $this->dateFormat($provider->getDateCreated()); ?></small>
        </h1>
    </div>
</div>

<!--Tabs-->
<div class="row">
    <hr style="height: 4px; width: 100%; background: rgb(224, 226, 229); border: none; margin: 0; ">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link <?= ($activeTab === 'info') ? 'active' : ''; ?>"
               href="<?= $this->url('providers/info', ['id' => $provider->getId()]); ?>">Информация</a>
        </li>
        <li class="nav-item">
            <a class="nav-link <?= ($activeTab === 'tariffs') ? 'active' : ''; ?>"
               href="<?= $this->url('tariffs/provider', ['id' => $provider->getId()]); ?>">Тарифы</a>
        </li>
        <li class="nav-item">
            <a class="nav-link <?= ($activeTab === 'invoices') ? 'active' : ''; ?>"
               href="<?= $this->url('invoices/provider', ['id' => $provider->getId()]); ?>">Счета</a>
        </li>
        <li class="nav-item">
            <a class="nav-link <?= ($activeTab === 'users') ? 'active' : ''; ?>"
               href="<?= $this->url('users/provider', ['id' => $provider->getId()]); ?>">Пользователи</a>
        </li>
    </ul>
</div>
