<?php
/**
 * @var \Application\Entity\Provider $provider
 */
?>
<tr>
    <td>
        <a href="<?=$this->url('providers/info', ['id' => $provider->getId()]); ?>" class="color-blue">
            <?= $provider->getFullName(); ?>
        </a>
    </td>
    <td><?= $provider->getInn(); ?></td>
    <td><?= $provider->getKpp(); ?></td>
    <td><?= $provider->getPhone(); ?></td>
    <td><?= $provider->getContactPerson(); ?></td>
    <td><?= $provider->getDateCreated()->format('d.m.Y'); ?></td>
    <td>

        <?php if($this->hasRole(['admin'])): ?>
            <button type="button" class="btn btn-link btn-secondary bmd-btn-fab-sm contragentEditBtn"
                    data-get-url="<?=$this->url('providers/get', ['id' => $provider->getId()]); ?>"
            >
                <i class="material-icons">mode_edit</i>
            </button>
        <?php endif; ?>
    </td>
</tr>
