<?php
/**
 * @var \Application\Entity\Provider $provider
 */
?>
<tr>
    <td>
        <a href="<?=$this->url('providers', ['id' => $provider->getId(), 'action' => 'info']); ?>" class="color-blue">
            <?= $provider->getFullName(); ?>
        </a>
    </td>
    <td><?= $provider->getInn(); ?></td>
    <td><?= $provider->getKpp(); ?></td>
    <td><?= $provider->getPhone(); ?></td>
    <td><?= $provider->getContactPerson(); ?></td>
    <td><?= $provider->getDateCreated()->format('d.m.Y'); ?></td>
    <td><?= $provider->getEtpContractNumber(); ?> от <?= $provider->getEtpContractDate()->format('d.m.Y'); ?></td>
    <td>
        <button type="button" class="btn btn-link btn-secondary bmd-btn-fab-sm contragentEditBtn"
                data-get-url="<?=$this->url('providers', ['id' => $provider->getId(), 'action' => 'get']); ?>"
        >
            <i class="material-icons">mode_edit</i>
        </button>
    </td>
</tr>
