<?php
/**
 * @var \Application\Entity\Client   $client
 * @var \Application\Entity\Tariff[] $tariffs
 * @var string                       $activeTab
 */

/** @var \Application\View\Helper\Navigation\Navbar $menu */
$menu = $this->navigation('Zend\Navigation\Default')->Navbar();
$menu->setActiveItemId('tariffs');

$this->headLink()->appendStylesheet($this->basePath('css/contragents.css'));
$this->inlineScript()->appendFile($this->basePath('js/tariffs.js'));

$statuses = \Application\Entity\Tariff::getStatuses();
?>

<!--client info-->
<div class="contragent_info">
    <?php
    /*echo $this->partial('application/clients/partial/header', [
        'client'    => $client,
        'activeTab' => $activeTab,
    ]);*/
    ?>

    <?php if (empty($tariffs)): ?>
        <div class="alert alert-dark" role="alert">
            Нет данных для отображения
        </div>
    <?php else: ?>
        <div class="row tariffs_accordion" id="accordion">
            <div class="col-12">
                <?php foreach ($tariffs as $tariff): ?>
                    <?= $this->partial('application/tariffs/partial/row', [
                        'tariff' => $tariff,
                    ]); ?>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif; ?>
</div>
