<?php
/**
 * @var \Application\Entity\Client   $client
 * @var \Application\Entity\Tariff[] $tariffs
 * @var string                       $activeTab
 * @var string                       $activeStatus
 */

/** @var \Application\View\Helper\Navigation\Navbar $menu */
$menu = $this->navigation('Zend\Navigation\Default')->Navbar();
$menu->setActiveItemId('tariffs');

$this->headLink()->appendStylesheet($this->basePath('css/contragents.css'));
$this->inlineScript()->appendFile($this->basePath('js/tariffs.js'));

$statuses = \Application\Entity\Tariff::getStatuses();
?>

<!--client info-->
<div class="contragent_info">
    <?= $this->partial('application/clients/partial/header', [
        'client'    => $client,
        'activeTab' => $activeTab,
    ]); ?>

    <div class="row">
        <div class="col-12">
            <div class="btn-group">
                <button class="btn dropdown-toggle" type="button" id="buttonMenu1" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                    <?= isset($statuses[$activeStatus]) ? $statuses[$activeStatus] : 'Все тарифы'; ?>
                </button>
                <div class="dropdown-menu" aria-labelledby="buttonMenu1">
                    <a class="dropdown-item"
                       href="<?= $this->url('tariffs/client', ['id' => $client->getId()]); ?>">Все</a>
                    <?php foreach ($statuses as $statusKey => $statusTitle): ?>
                        <a class="dropdown-item"
                           href="<?= $this->url('tariffs/client', ['id' => $client->getId()], ['query' => 'status=' . $statusKey]); ?>">
                            <?= $statusTitle ?>
                        </a>
                    <?php endforeach;; ?>
                </div>
            </div>
        </div>
    </div>

    <?php if (empty($tariffs)): ?>
        <div class="alert alert-dark" role="alert">
            Нет данных для отображения
        </div>
    <?php else: ?>
        <div class="row tariffs_accordion" id="accordion">
            <div class="col-12">
                <?php foreach ($tariffs as $tariff): ?>
                    <?= $this->partial('application/tariffs/partial/row', [
                        'tariff' => $tariff,
                    ]); ?>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif; ?>
</div>
