<?php
/**
 * @var \Application\Entity\Client    $client
 * @var \Application\Entity\Invoice[] $invoices
 * @var string                        $activeTab
 * @var string                        $activeStatus
 */

/** @var \Application\View\Helper\Navigation\Navbar $menu */
$menu = $this->navigation('Zend\Navigation\Default')->Navbar();
$menu->setActiveItemId('invoices');

$this->headLink()->appendStylesheet($this->basePath('css/contragents.css'));
$this->inlineScript()->appendFile($this->basePath('js/invoices.js'));

$statuses = \Application\Entity\Invoice::getStatuses();
?>

<!--provider info-->
<div class="contragent_info">
    <?= $this->partial('application/clients/partial/header', [
        'client'    => $client,
        'activeTab' => $activeTab,
    ]); ?>

    <div class="row">
        <div class="col-12">
            <div class="btn-group">
                <button class="btn dropdown-toggle" type="button" id="buttonMenu1" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                    <?= isset($statuses[$activeStatus]) ? $statuses[$activeStatus] : 'Все счета'; ?>
                </button>
                <div class="dropdown-menu" aria-labelledby="buttonMenu1">
                    <a class="dropdown-item"
                       href="<?= $this->url('invoices/client', ['id' => $client->getId()]); ?>">Все</a>
                    <?php foreach ($statuses as $statusKey => $statusTitle): ?>
                        <a class="dropdown-item"
                           href="<?= $this->url('invoices/client', ['id' => $client->getId()], ['query' => 'status=' . $statusKey]); ?>">
                            <?= $statusTitle ?>
                        </a>
                    <?php endforeach;; ?>
                </div>
            </div>
        </div>
    </div>

    <?php if (empty($invoices)): ?>
        <div class="alert alert-dark" role="alert">
            Нет данных для отображения
        </div>
    <?php else: ?>
        <div class="row invoices_accordion" id="accordion">
            <div class="col-12">
                <?php foreach ($invoices as $invoice): ?>
                    <?= $this->partial('application/invoices/partial/row', [
                        'invoice' => $invoice,
                    ]); ?>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif; ?>
</div>
