<?php
/**
 * @var \Application\Entity\Invoice[] $invoices
 * @var array                         $queryParams
 */

$this->headLink()->appendStylesheet($this->basePath('css/contragents.css'));
$this->inlineScript()->appendFile($this->basePath('js/invoices.js'));

$statuses = \Application\Entity\Invoice::getStatuses();
?>

<!--provider info-->
<div class="contragent_info">
    <?= $this->partial('application/invoices/partial/filter', [
        'queryParams' => $queryParams,
    ]); ?>

    <?php if (empty($invoices)): ?>
        <div class="alert alert-dark" role="alert">
            Нет данных для отображения
        </div>
    <?php else: ?>
        <div class="row invoices_accordion" id="accordion">
            <div class="col-12">
                <?php foreach ($invoices as $invoice): ?>
                    <?= $this->partial('application/invoices/partial/row', [
                        'invoice' => $invoice,
                    ]); ?>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif; ?>
</div>

