<?php
/**
 * @var \Application\Form\InvoiceForm $invoiceForm
 * @var \Application\Entity\Provider  $provider
 * @var \Application\Entity\Invoice[] $invoices
 * @var string                        $activeTab
 * @var array                         $queryParams
 */

/** @var \Application\View\Helper\Navigation\Navbar $menu */
$menu = $this->navigation('Zend\Navigation\Default')->Navbar();
$menu->setActiveItemId('invoices');

$this->headLink()->appendStylesheet($this->basePath('css/contragents.css'));
$this->inlineScript()->appendFile($this->basePath('js/invoices.js'));
?>

<!--provider info-->
<div class="contragent_info">
    <?= $this->partial('application/providers/partial/header', [
        'provider'  => $provider,
        'activeTab' => $activeTab,
    ]); ?>

    <?= $this->partial('application/invoices/partial/filter', [
        'queryParams' => $queryParams,
    ]); ?>

    <?php if (empty($invoices)): ?>
        <div class="alert alert-dark" role="alert">
            Нет данных для отображения
        </div>
    <?php else: ?>
        <div class="row invoices_accordion" id="accordion">
            <div class="col-12">
                <?php foreach ($invoices as $invoice): ?>
                    <?= $this->partial('application/invoices/partial/row', [
                        'invoice' => $invoice,
                    ]); ?>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif; ?>
</div>

<!-- Modal add new invoice -->
<?= $this->partial('application/invoices/partial/modal', [
    'invoiceForm' => $invoiceForm,
]); ?>
