<?php
/**
 * @var \Application\Form\InvoiceForm $invoiceForm
 * @var \Application\Entity\Provider  $provider
 * @var \Application\Entity\Invoice[] $invoices
 * @var string                        $activeTab
 * @var string                        $activeStatus
 */

/** @var \Application\View\Helper\Navigation\Navbar $menu */
$menu = $this->navigation('Zend\Navigation\Default')->Navbar();
$menu->setActiveItemId('providers');

$this->headLink()->appendStylesheet($this->basePath('css/contragents.css'));
$this->inlineScript()->appendFile($this->basePath('js/invoices.js'));

$statuses = \Application\Entity\Invoice::getStatuses();
?>

<!--provider info-->
<div class="contragent_info">
    <?= $this->partial('application/providers/partial/header', [
        'provider'  => $provider,
        'activeTab' => $activeTab,
    ]); ?>

    <div class="row">
        <div class="col-8">
            <div class="btn-group">
                <button class="btn dropdown-toggle" type="button" id="buttonMenu1" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                    <?= isset($statuses[$activeStatus]) ? $statuses[$activeStatus] : 'Все счета'; ?>
                </button>
                <div class="dropdown-menu" aria-labelledby="buttonMenu1">
                    <a class="dropdown-item"
                       href="<?= $this->url('invoices/provider', ['id' => $provider->getId()]); ?>">Все</a>
                    <?php foreach ($statuses as $statusKey => $statusTitle): ?>
                        <a class="dropdown-item"
                           href="<?= $this->url('invoices/provider', ['id' => $provider->getId()], ['query' => 'status=' . $statusKey]); ?>">
                            <?= $statusTitle ?>
                        </a>
                    <?php endforeach;; ?>
                </div>
            </div>
        </div>
        <div class="col-4 text-right">
            <button type="button" class="btn btn-raised btn-primary btn-blue pull-right" id="addInvoiceBtn">
                Выставить счет
            </button>
        </div>
    </div>

    <?php if (empty($invoices)): ?>
        <div class="alert alert-dark" role="alert">
            Нет данных для отображения
        </div>
    <?php else: ?>
        <div class="row invoices_accordion" id="accordion">
            <div class="col-12">
                <?php foreach ($invoices as $invoice): ?>
                    <?= $this->partial('application/invoices/partial/row', [
                        'invoice' => $invoice,
                    ]); ?>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif; ?>
</div>

<!-- Modal add new invoice -->
<?= $this->partial('application/invoices/partial/modal', [
    'invoiceForm' => $invoiceForm,
]); ?>
