<?php
/**
 * @var \Zend\Form\Form $updateUserForm
 */


$csrfField = $updateUserForm->get('csrf');

$idField = $updateUserForm->get('id');
$idField->setAttribute('id', 'id_edit');

$surnameField = $updateUserForm->get('surname');
$surnameField->setAttribute('id', 'surname_edit');

$nameField = $updateUserForm->get('name');
$nameField->setAttribute('id', 'name_edit');

$patronymicField = $updateUserForm->get('patronymic');
$patronymicField->setAttribute('id', 'patronymic_edit');

$identityField = $updateUserForm->get('identity');
$identityField->setAttribute('id', 'identity_edit');

$submitBtn = $updateUserForm->get('submit');
?>

<div class="modal fade" id="updateUserModal" tabindex="-1" role="dialog" aria-labelledby="updateUserModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="updateUserModalLabel">Редактирование пользователя</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <?= $this->form()->openTag($updateUserForm); ?>

                <?=$this->formHidden($csrfField); ?>
                <?=$this->formHidden($idField); ?>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="<?= $surnameField->getAttribute('id'); ?>"
                                   class="bmd-label-floating"><?= $surnameField->getLabel(); ?></label>
                            <?= $this->formInput($surnameField); ?>
                            <div class="invalid-feedback"></div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="<?= $nameField->getAttribute('id'); ?>"
                                   class="bmd-label-floating"><?= $nameField->getLabel(); ?></label>
                            <?= $this->formInput($nameField); ?>
                            <div class="invalid-feedback"></div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="<?= $patronymicField->getAttribute('id'); ?>"
                           class="bmd-label-floating"><?= $patronymicField->getLabel(); ?></label>
                    <?= $this->formInput($patronymicField); ?>
                    <div class="invalid-feedback"></div>
                </div>

                <div class="form-group">
                    <label for="<?= $identityField->getAttribute('id'); ?>"
                           class="bmd-label-floating"><?= $identityField->getLabel(); ?></label>
                    <?= $this->formInput($identityField); ?>
                    <div class="invalid-feedback"></div>
                </div>

                <div class="alert alert-warning error-msg" role="alert" style="display: none;"></div>

                <button type="button" class="btn btn-primary btn-raised btn-blue btn-block" disabled
                        id="updateUserSaveBtn"
                        data-save-url="<?=$this->url('zfbuser/api/update-user', ['id' => ':id']); ?>"
                        name="<?= $submitBtn->getName(); ?>"><?= $submitBtn->getLabel(); ?></button>

                <?= $this->form()->closeTag(); ?>

            </div>
            <div class="modal-footer"></div>
        </div>
    </div>
</div>
