<?php
/**
 * @var \Zend\Form\Form $newUserForm
 */


$csrfField = $newUserForm->get('csrf');
$typeField = $newUserForm->get('type');

$surnameField = $newUserForm->get('surname');
$surnameField->setAttribute('id', 'surname');

$nameField = $newUserForm->get('name');
$nameField->setAttribute('id', 'name');

$patronymicField = $newUserForm->get('patronymic');
$patronymicField->setAttribute('id', 'patronymic');

$identityField = $newUserForm->get('identity');
$identityField->setAttribute('id', 'identity');

$providerField = $newUserForm->get('provider_id');
$providerField->setAttribute('id', 'provider_id');

$trackerField = $newUserForm->get('tracker_id');
$trackerField->setAttribute('id', 'tracker_id');

$submitBtn = $newUserForm->get('submit');
?>

<!-- Modal add new user -->
<div class="modal fade" id="userModal" tabindex="-1" role="dialog" aria-labelledby="userModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="userModalLabel">Добавление нового пользователя</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <?= $this->form()->openTag($newUserForm); ?>

                <?=$this->formHidden($csrfField); ?>
                <?=$this->formHidden($typeField); ?>
                <?=$this->formHidden($providerField); ?>
                <?=$this->formHidden($trackerField); ?>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="<?= $surnameField->getAttribute('id'); ?>"
                                   class="bmd-label-floating"><?= $surnameField->getLabel(); ?></label>
                            <?= $this->formInput($surnameField); ?>
                            <div class="invalid-feedback"></div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="<?= $nameField->getAttribute('id'); ?>"
                                   class="bmd-label-floating"><?= $nameField->getLabel(); ?></label>
                            <?= $this->formInput($nameField); ?>
                            <div class="invalid-feedback"></div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="<?= $patronymicField->getAttribute('id'); ?>"
                           class="bmd-label-floating"><?= $patronymicField->getLabel(); ?></label>
                    <?= $this->formInput($patronymicField); ?>
                    <div class="invalid-feedback"></div>
                </div>

                <div class="form-group">
                    <label for="<?= $identityField->getAttribute('id'); ?>"
                           class="bmd-label-floating"><?= $identityField->getLabel(); ?></label>
                    <?= $this->formInput($identityField); ?>
                    <div class="invalid-feedback"></div>
                </div>

                <div class="alert alert-warning error-msg" role="alert" style="display: none;"></div>

                <button type="button" class="btn btn-primary btn-raised btn-blue btn-block" disabled
                        id="userSaveBtn"
                        data-save-url="<?=$this->url('zfbuser/api/new-user'); ?>?type=user"
                        name="<?= $submitBtn->getName(); ?>"><?= $submitBtn->getLabel(); ?></button>

                <?= $this->form()->closeTag(); ?>

            </div>
            <div class="modal-footer"></div>
        </div>
    </div>
</div>
