<?php
/**
 * @var \Application\Entity\Provider[]       $providers
 * @var \Application\Form\NewProviderForm    $newProviderForm
 * @var \Application\Form\EditProviderForm   $editProviderForm
 * @var \Application\Form\ProviderConfigForm $configForm
 * @var string                               $search значение поискового поля
 */

$this->headLink()->appendStylesheet($this->basePath('css/contragents.css'));
$this->inlineScript()->appendFile($this->basePath('js/contragents.js'));
?>
<div class="row mb-3">
    <div class="col-md-5">
        <form class="form" action="?" method="get">
            <div class="input-group search-input-group">
                <div class="input-group-prepend">
                    <div class="input-group-text"><i class="material-icons">&#xE8B6;</i></div>
                </div>
                <input class="form-control search-field" type="text" name="search"
                       placeholder="Поиск по названию или ИНН" value="<?= $search; ?>">
            </div>

            <!--For submit by enter key-->
            <input type="submit" style="display:none"/>
        </form>
    </div>
    <div class="col-md-3">
    </div>
    <div class="col-md-4 text-right">
        <?php if ($this->hasRole(['admin'])): ?>
            <button type="button" class="btn btn-raised btn-primary btn-blue" id="addContragentBtn">
                Добавить
            </button>
        <?php endif; ?>
    </div>
</div>

<?php if (empty($providers)): ?>
    <div class="alert alert-dark" role="alert">
        Нет данных для отображения
    </div>
<?php else: ?>
    <table class="table table-hover table-contragents">
        <thead>
        <tr>
            <th>Наименование провайдера</th>
            <th>ИНН</th>
            <th>КПП</th>
            <th>Телефон</th>
            <th>Контактное лицо</th>
            <th>Дата регистрации</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <tbody>
        <?php foreach ($providers as $provider): ?>
            <?= $this->partial('application/providers/partial/row', [
                'provider' => $provider,
            ]); ?>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<?php if ($this->hasRole(['admin'])): ?>
    <!-- Modal add new provider and user -->
    <?= $this->partial('application/providers/partial/modal', [
        'newProviderForm' => $newProviderForm,
    ]); ?>

    <!-- Modal edit provider -->
    <?= $this->partial('application/providers/partial/editModal', [
        'editProviderForm' => $editProviderForm,
    ]); ?>

    <!-- Modal edit provider config -->
    <?= $this->partial('application/providers/partial/configModal', [
        'configForm' => $configForm,
    ]); ?>
<?php endif; ?>
