<?php
/**
 * @var \Application\Entity\Provider $provider
 * @var string                       $activeTab
 */

$this->headLink()->appendStylesheet($this->basePath('css/providers.css'));
$this->inlineScript()->appendFile($this->basePath('js/providers.js'));
?>

<!--provider info-->
<div class="provider_info">
    <?= $this->partial('application/providers/partial/header', [
        'provider'  => $provider,
        'activeTab' => $activeTab,
    ]); ?>

    <!--Инфо провайдера-->
    <div class="row">
        <div class="col-md-4 col-sm-6 col-xs-6">
            <p class="label">ИНН</p>
            <p class="label">КПП</p>
            <p class="label">Дата заключения договора</p>
        </div>
        <div class="col-md-8 col-sm-6 col-xs-6">
            <p class="value"><?= $provider->getInn(); ?></p>
            <p class="value"><?= $provider->getKpp(); ?></p>
            <p class="value"><?= $provider->getEtpContractDate()->format('d.m.Y'); ?></p>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <p class="contact_header">Контакты</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 col-sm-6 col-xs-6">
            <p class="label">Контактное лицо</p>
            <p class="label">Телефон</p>
            <p class="label">Email</p>
        </div>
        <div class="col-md-8 col-sm-6 col-xs-6">
            <p class="value"><?= $provider->getContactPerson(); ?></p>
            <p class="value"><?= $provider->getPhone(); ?></p>
            <p class="value"><?= $provider->getEmail(); ?></p>
        </div>
    </div>
</div>