<?php
/**
 * @var \Application\Entity\Provider   $provider
 * @var \Application\Entity\Contract[] $contracts
 * @var string                         $activeTab
 */

/** @var \Application\View\Helper\Navigation\Navbar $menu */
$menu = $this->navigation('Zend\Navigation\Default')->Navbar();
$menu->setActiveItemId('providers');

$this->headLink()->appendStylesheet($this->basePath('css/contragents.css'));
$this->inlineScript()->appendFile($this->basePath('js/contragents.js'));
?>

<!--provider info-->
<div class="contragent_info">
    <?= $this->partial('application/providers/partial/header', [
        'provider'  => $provider,
        'activeTab' => $activeTab,
    ]); ?>

    <!--Инфо провайдера-->
    <div class="row">
        <div class="col-md-4 col-sm-6 col-6">
            <p class="label">ИНН</p>
            <p class="label">КПП</p>
            <p class="label">Юридический адрес</p>
        </div>
        <div class="col-md-8 col-sm-6 col-6">
            <p class="value"><?= $provider->getInn(); ?></p>
            <p class="value"><?= $provider->getKpp(); ?></p>
            <p class="value"><?= $provider->getAddress(); ?></p>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <p class="contact_header">Контакты</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 col-sm-6 col-6">
            <p class="label">Контактное лицо</p>
            <p class="label">Телефон</p>
            <p class="label">Email</p>
        </div>
        <div class="col-md-8 col-sm-6 col-6">
            <p class="value"><?= $provider->getContactPerson(); ?></p>
            <p class="value"><?= $provider->getPhone(); ?></p>
            <p class="value"><?= $provider->getEmail(); ?></p>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <p class="contact_header">Договоры</p>
            <?php foreach ($contracts as $contract): ?>
                <p class="label"><?=$contract->getDisplayName(); ?></p>
            <?php endforeach;; ?>
        </div>
    </div>
</div>
