<?php
/**
 * @var \Application\Form\TariffForm $tariffForm
 * @var \Application\Entity\Provider $provider
 * @var \Application\Entity\Tariff[] $tariffs
 * @var string                       $activeTab
 * @var string                       $activeStatus
 */

$this->headLink()->appendStylesheet($this->basePath('css/providers.css'));
$this->inlineScript()->appendFile($this->basePath('js/tariffs.js'));

$statuses = \Application\Entity\Tariff::getStatuses();
?>

<!--provider info-->
<div class="provider_info">
    <?= $this->partial('application/providers/partial/header', [
        'provider'  => $provider,
        'activeTab' => $activeTab,
    ]); ?>

    <div class="row">
        <div class="col-8">
            <div class="btn-group">
                <button class="btn dropdown-toggle" type="button" id="buttonMenu1" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                    <?= isset($statuses[$activeStatus]) ? $statuses[$activeStatus] : 'Все тарифы'; ?>
                </button>
                <div class="dropdown-menu" aria-labelledby="buttonMenu1">
                    <a class="dropdown-item"
                       href="<?= $this->url('providers', ['id' => $provider->getId(), 'action' => 'tariffs']); ?>">Все</a>
                    <?php foreach ($statuses as $statusKey => $statusTitle): ?>
                        <a class="dropdown-item"
                           href="<?= $this->url('providers', ['id' => $provider->getId(), 'action' => 'tariffs'], ['query' => 'status=' . $statusKey]); ?>">
                            <?= $statusTitle ?>
                        </a>
                    <?php endforeach;; ?>
                </div>
            </div>
        </div>
        <div class="col-4 text-right">
            <button type="button" class="btn btn-raised btn-primary btn-add pull-right" id="addTariffBtn">Добавить тариф</button>
        </div>
    </div>

    <?php if (empty($tariffs)): ?>
        <div class="alert alert-dark" role="alert">
            Нет данных для отображения
        </div>
    <?php else: ?>
        <div class="row tariffs_accordion" id="accordion">
            <div class="col-12">
                <?php foreach ($tariffs as $tariff): ?>
                    <?= $this->partial('application/providers/partial/tariffRow', [
                        'tariff' => $tariff,
                    ]); ?>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif; ?>
</div>

<!-- Modal add new tariff -->
<?= $this->partial('application/providers/partial/tariffModal', [
    'tariffForm' => $tariffForm,
]); ?>
