<?php
/**
 * @var \Application\Form\TariffForm $tariffForm
 * @var \Application\Entity\Provider $provider
 * @var \Application\Entity\Tariff[] $tariffs
 * @var string                       $activeTab
 * @var string                       $activeStatus
 */

$this->headLink()->appendStylesheet($this->basePath('css/providers.css'));
$this->inlineScript()->appendFile($this->basePath('js/tariffs.js'));

$statuses = \Application\Entity\Tariff::getStatuses();
?>

<!--provider info-->
<div class="provider_info">
    <?= $this->partial('application/providers/partial/header', [
        'provider'  => $provider,
        'activeTab' => $activeTab,
    ]); ?>

    <div class="row">
        <div class="col-8">
            <div class="btn-group">
                <button class="btn dropdown-toggle" type="button" id="buttonMenu1" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                    <?= isset($statuses[$activeStatus]) ? $statuses[$activeStatus] : 'Все тарифы'; ?>
                </button>
                <div class="dropdown-menu" aria-labelledby="buttonMenu1">
                    <a class="dropdown-item"
                       href="<?= $this->url('providers', ['id' => $provider->getId(), 'action' => 'tariffs']); ?>">Все</a>
                    <?php foreach ($statuses as $statusKey => $statusTitle): ?>
                        <a class="dropdown-item"
                           href="<?= $this->url('providers', ['id' => $provider->getId(), 'action' => 'tariffs'], ['query' => 'status=' . $statusKey]); ?>">
                            <?= $statusTitle ?>
                        </a>
                    <?php endforeach;; ?>
                </div>
            </div>
        </div>
        <div class="col-4 text-right">
            <button type="button" class="btn btn-raised btn-primary btn-add pull-right" id="addTariffBtn">Добавить тариф
            </button>
        </div>
    </div>

    <?php if (empty($tariffs)): ?>
        <div class="alert alert-dark" role="alert">
            Нет данных для отображения
        </div>
    <?php else: ?>
        <div class="row tariffs_accordion" id="accordion">
            <div class="col-12">
                <?php foreach ($tariffs as $tariff): ?>
                    <div class="card">
                        <div class="card-header" id="tariff_<?= $tariff->getId(); ?>">
                            <div class="row" data-toggle="collapse" data-target="#collapse<?= $tariff->getId(); ?>"
                                 aria-expanded="false" aria-controls="collapse<?= $tariff->getId(); ?>">
                                <div class="col-xl-10 col-md-8 col-sm-8 col-xs-6">
                                    <h5 class="name"><?= $tariff->getName(); ?></h5>
                                    <h6 class="desc"><?= $tariff->getDescription(); ?></h6>
                                </div>
                                <div class="col-xl-2 col-md-4 col-sm-4 col-xs-6 text-right">
                                    <p class="cost"><?= money_format('%.2n', $tariff->getCost()); ?> <?= $tariff->getCurrency(); ?></p>
                                    <p class="nds">
                                        <?php if($tariff->getNds() === null): ?>
                                        Без НДС
                                        <?php else: ?>
                                            <?= $tariff->getNds(); ?>%
                                        <?php endif; ?>
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div id="collapse<?= $tariff->getId(); ?>" class="collapse"
                             aria-labelledby="heading<?= $tariff->getId(); ?>" data-parent="#accordion">
                            <div class="card-body">
                                <button type="button" class="btn btn-raised tariffEditBtn"
                                        data-id="<?=$tariff->getId(); ?>"
                                        data-get-url="<?=$this->url('tariffs', ['id' => $tariff->getId(), 'action' => 'get']); ?>"
                                >Редактировать</button>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif; ?>
</div>

<!-- Modal add new tariff -->
<?= $this->partial('application/providers/partial/tariffModal', [
    'tariffForm' => $tariffForm,
]); ?>
