<?php
/**
 * @var \Application\Entity\Tracker[]     $trackers
 * @var \Application\Form\NewTrackerForm  $newTrackerForm
 * @var \Application\Form\EditTrackerForm $editTrackerForm
 * @var string                            $search значение поискового поля
 */

$this->headLink()->appendStylesheet($this->basePath('css/contragents.css'));
$this->inlineScript()->appendFile($this->basePath('js/contragents.js'));
?>
<div class="row mb-3">
    <div class="col-md-5">
        <form class="form" action="?" method="get">
            <div class="input-group search-input-group">
                <div class="input-group-prepend">
                    <div class="input-group-text"><i class="material-icons">&#xE8B6;</i></div>
                </div>
                <input class="form-control search-field" type="text" name="search" placeholder="Поиск по названию или ИНН" value="<?= $search; ?>">
            </div>

            <!--For submit by enter key-->
            <input type="submit" style="display:none"/>
        </form>
    </div>
    <div class="col-md-3">
    </div>
    <div class="col-md-4 text-right">
        <button type="button" class="btn btn-raised btn-primary btn-blue" id="addContragentBtn">
            Добавить
        </button>
    </div>
</div>

<?php if(empty($trackers)): ?>
    <div class="alert alert-dark" role="alert">
        Нет данных для отображения
    </div>
<?php else: ?>
    <table class="table table-hover table-contragents">
        <thead>
        <tr>
            <th>Наименование организации</th>
            <th>ИНН</th>
            <th>КПП</th>
            <th>Телефон</th>
            <th>Контактное лицо</th>
            <th>Дата регистрации</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <tbody>
        <?php foreach ($trackers as $tracker): ?>
            <?= $this->partial('application/trackers/partial/row', [
                'tracker' => $tracker,
            ]); ?>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<!-- Modal add new tracker and user -->
<?= $this->partial('application/trackers/partial/modal', [
        'newTrackerForm' => $newTrackerForm,
]); ?>

<!-- Modal edit tracker -->
<?= $this->partial('application/trackers/partial/editTrackerModal', [
        'editTrackerForm' => $editTrackerForm,
]); ?>
