<?php
/**
 * @var \Application\Entity\Tracker $tracker
 * @var string                      $activeTab
 */

$this->headLink()->appendStylesheet($this->basePath('css/contragents.css'));
$this->inlineScript()->appendFile($this->basePath('js/contragents.js'));
?>

<!--provider info-->
<div class="contragent_info">
    <?= $this->partial('application/trackers/partial/header', [
        'tracker'   => $tracker,
        'activeTab' => $activeTab,
    ]); ?>

    <!--Инфо организации-->
    <div class="row">
        <div class="col-md-4 col-sm-6 col-6">
            <p class="label">ИНН</p>
            <p class="label">КПП</p>
        </div>
        <div class="col-md-8 col-sm-6 col-6">
            <p class="value"><?= $tracker->getInn(); ?></p>
            <p class="value"><?= $tracker->getKpp(); ?></p>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <p class="contact_header">Контакты</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 col-sm-6 col-6">
            <p class="label">Контактное лицо</p>
            <p class="label">Телефон</p>
            <p class="label">Email</p>
        </div>
        <div class="col-md-8 col-sm-6 col-6">
            <p class="value"><?= $tracker->getContactPerson(); ?></p>
            <p class="value"><?= $tracker->getPhone(); ?></p>
            <p class="value"><?= $tracker->getEmail(); ?></p>
        </div>
    </div>
</div>
